# Generated by Django 3.0.3 on 2020-05-12 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_auto_20200507_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('travel blogs', 'Travel Blogs'), ('fashion blogs', 'Fashion Blogs'), ('food blogs', 'Food Blogs'), ('educational blogs', 'Educational Blogs'), ('parenting blogs', 'Parenting Blogs'), ('movie and music blogs', 'Movie And Music Blogs'), ('sports blogs', 'Sports Blogs'), ('personal blogs', 'Personal Blogs'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
