# Generated by Django 3.0.3 on 2020-05-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='title',
        ),
    ]
