# Generated by Django 3.0.3 on 2020-05-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200529_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
