# Generated by Django 3.0.3 on 2020-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='avatar2.jpg', upload_to='images/'),
        ),
    ]
