# Generated by Django 3.0.3 on 2020-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20200529_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='def.jpeg', upload_to='images/'),
        ),
    ]
