# Generated by Django 3.0.3 on 2020-05-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20200529_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='images/def.jpeg', upload_to='images/'),
        ),
    ]
