# Generated by Django 3.0.3 on 2020-05-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20200530_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='media/images/def.jpeg', upload_to='images/'),
        ),
    ]
