# Generated by Django 3.0.3 on 2020-05-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20200530_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='blogger.jpg', upload_to='images/'),
        ),
    ]
